feat: insert code basic controller create client
Poketnans/metamorfo-tattoo pull request #12
Opened 2022-03-03 01:07 UTC by BeatrixFox

I tested this function through a fake route.

2022-03-03 02:19 UTC, Poketnans reviewed
Seguem alguns pontos de correção. A lógica geral está top!

2022-03-03 02:19 UTC, Poketnans commented on app/controllers/clients_controllers/post_create.py
> +            'password_hash': str,
Este campo `password_hash` não será fornecido pelo usuário. Será fornecido uma senha ( `password` ) e a partir dela será criado um `hash` usando a biblioteca `werkzeug` dentro da própria model usando-se de getter e setter. Verificar em `Notion > Referências > Hashing` para exemplo. Quem pegar essa model para trabalhar, deverá criar essa mecânica.

2022-03-03 02:19 UTC, Poketnans commented on app/controllers/clients_controllers/post_create.py
> +        return jsonify(err.description), err.code
Aqui é melhor usar as exceções personalizadas ( em `app.errors` ). Mesmo sabendo que ambas herdam de BadRequest, elas esclarecem melhor quais erros estão sendo tratados.

2022-03-03 02:19 UTC, Poketnans commented on app/controllers/clients_controllers/post_create.py
> +        return {"error key": f"key invalid {err}"}, HTTPStatus.BAD_REQUEST
Se este erro estiver relacionado a chaves extra fornecidos pelo usuário da API, a função `payload_eval` já faz um filtro ignorando essas chaves.

2022-03-03 02:37 UTC, Poketnans commented on app/controllers/clients_controllers/post_create.py
> +from flask import current_app, jsonify, request
No `app.classes.app_with_db` existe uma instância do `current_app` que está tipada. Assim o intellisence pode te ajudar quando tentar acessar o `db`.

2022-03-04 14:47 UTC, cricardolima commented
A princípío, tudo ok. Todas as sugestões foram atendidas.

2022-03-04 15:08 UTC, Poketnans requested changes

2022-03-04 15:08 UTC, Poketnans commented on app/controllers/clients_controllers/post_create.py
> +            return jsonify(DataAlreadyExistsError.description), HTTPStatus.CONFLICT
Não énecessário o uso das exceções personalizadas nos casos de elas não serem levantadas ( `raise` ) para podermos capturá-la com o `except`. No caso, pode-se construir paylaod de resposta no próprio `if`.

2022-03-04 15:08 UTC, Poketnans commented on app/controllers/clients_controllers/post_create.py
> +        return BadRequisiton
Esse retorno não etá como esperado. Espera-se um objeto JSONIFY e um status code. No caso está retornando apenas a classe da exceção `BadRequisition`.

2022-03-04 19:22 UTC, merged