fix: tattoooists model refactored due to today's meeting
Poketnans/metamorfo-tattoo pull request #18
Opened 2022-03-03 18:38 UTC by pedromenimen

2022-03-03 19:10 UTC, BaiduAV commented
Tá tudo certo, só não precisa serializar esses dados, então pode tirar a tipagem das colunas

2022-03-03 19:32 UTC, Poketnans requested changes

2022-03-03 19:32 UTC, Poketnans commented on app/models/tattooists_model.py
> +    image_mimetype = Column(String)
É necessário implementar a lógica para geração do link da image usando getter, como demonstrado na reunião. Assim será criado um outro atributo `url_image` que será alimentado por essa mecânica. Esse novo atributo retornará n aresposta da requisição. Conferir o payload na task de Product Backlog. Conferir com Bruno o modelo de implementação.

2022-03-03 20:59 UTC, Poketnans requested changes
Apenas um detalhe na URL

2022-03-03 20:59 UTC, Poketnans commented on app/models/tattooists_model.py
> +    def url_image(self, text = "http://localhost:5000/tattooists/profile_pricture/"):
Ajustar na URL a parte "/profile_pricture" para "/profile_image" para deixar padronizado com o atributo.

2022-03-04 00:12 UTC, Poketnans approved these changes
Deu bom!

2022-03-04 00:14 UTC, merged