Feature/controller tattoists get by
Poketnans/metamorfo-tattoo pull request #37
Opened 2022-03-05 15:24 UTC by BeatrixFox

2022-03-05 17:43 UTC, Poketnans approved these changes

2022-03-05 17:45 UTC, Brunoro811 requested changes
O retonro caso nao encontre pelo id deve retornar um not found. Não tem bo backlog mas vamos adicionar la

2022-03-05 17:45 UTC, Poketnans requested changes

2022-03-05 17:45 UTC, Poketnans commented on app/controllers/tattooists_controllers/get_specific.py
> +        return jsonify([]), HTTPStatus.OK
Nesse caso, é necessário retornar um NotFound. Como é uma rota para trazer um recurso específico, não faz sentido retornar uma lista não vazia.

2022-03-05 18:13 UTC, cricardolima approved these changes
Bom ajuste. Condizente com proposto.

Edit: Segundo definido no Backlog, ao invés de usar "error_message", utilize "msg" nas descrições.

2022-03-05 21:23 UTC, BeatrixFox commented on app/controllers/tattooists_controllers/get_specific.py
> +        return jsonify([]), HTTPStatus.OK
Ajustes efetuados como solicitado

2022-03-06 00:12 UTC, Poketnans approved these changes
Tudo certo!

2022-03-06 00:12 UTC, merged