feat: get specific tattoo working as expected
Poketnans/metamorfo-tattoo pull request #42
Opened 2022-03-05 18:47 UTC by pedromenimen

2022-03-05 20:11 UTC, BaiduAV approved these changes
Boa, merge autorizado 👍🏼

2022-03-06 00:35 UTC, Poketnans requested changes

2022-03-06 00:35 UTC, Poketnans commented on app/controllers/tattoos_controllers/get_specific.py
> +        ), HTTPStatus.OK
Necessário rever a construção desse payload. Trataremos disso na próxima reunião, mas basicamente, utilizaremos dos dataclasses + relationships para serializar essas models aninhadas. 👍🏼

2022-03-06 16:03 UTC, Poketnans approved these changes
## Tudo certo.

2022-03-06 16:03 UTC, merged