fix: now the tatto needs at least one image to be created
Poketnans/metamorfo-tattoo pull request #84
Opened 2022-03-09 19:23 UTC by BaiduAV

2022-03-09 19:37 UTC, Poketnans approved these changes
Show

2022-03-09 19:50 UTC, Brunoro811 requested changes
O if criado deve ser um else em if files pois se não houver files a funcao get_files retorna None.

2022-03-09 19:50 UTC, Brunoro811 commented on app/controllers/tattoos_controllers/create.py
> +        if len(files) == 0:
Este if pode ser um else do if files. A função get_files() retorna uma lista de imagem se houver e None caso não haja.

2022-03-09 23:00 UTC, BaiduAV commented on app/controllers/tattoos_controllers/create.py
> +        if len(files) == 0:
Feito

2022-03-10 00:37 UTC, Poketnans approved these changes

2022-03-10 00:37 UTC, merged